# Generated by Django 3.2.4 on 2021-06-11 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('author', models.CharField(max_length=250)),
                ('publisher', models.CharField(max_length=250)),
                ('type', models.CharField(choices=[('ebook', 'ebook'), ('audiobook', 'audiobook')], max_length=250)),
                ('file_url', models.FileField(upload_to='media/book/')),
                ('thumbnail', models.ImageField(upload_to='media/thumbnails/')),
                ('tagline', models.CharField(max_length=250)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.category')),
            ],
        ),
    ]
