# Generated by Django 3.2.4 on 2021-06-11 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='due_date',
            field=models.DateField(null=True),
        ),
    ]
