# Generated by Django 3.2.4 on 2021-06-15 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='total_page',
            field=models.IntegerField(default=0),
        ),
    ]
